config/routes.rb
RsCalc::Application.routes.draw do

  devise_for :users

  resources :posts, :path => 'admin'

  match "posts/index", :as => :user_root

  get "api", :controller => :api, :action => 'index', :via => :get

  root :to => "home#index"

end

app/models/post.rb
# -*- coding: utf-8 -*-
class Post < ActiveRecord::Base
  attr_accessible :available, :linux, :users, :rate, :room, :unavailable, :windows, :calc_base

  validates :rate, :numericality => true, :inclusion => { :in => 0..100, :message => "利用者数や利用不可端末数を確認してみてください" }
  validates :users, :numericality => true, :presence => true
  validates :unavailable, :numericality => true, :presence => true
  validates :windows, :numericality => true, :presence => true
  validates :linux, :numericality => true, :presence => true

  def to_hash
    ActiveSupport::JSON.decode(self.to_json)
  end

  def to_api
    model = ActiveSupport::JSON.decode(self.to_json)

    h = Hash::new
    h[:rate] = self.rate
    h[:users] = self.users
    h[:available] = self.available
    h[:windows] = self.windows
    h[:linux] = self.linux
    h['outdated'] = Time.now - self.created_at > 1.hours # 有用なデータか?

    return h
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
  # :recoverable, :rememberable, :trackable, :validatable
  # devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
  
  if Rails.env.production?
     devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
  else
     devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :registerable 
  end

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  def index
    respond_to do |format|
      format.html
      format.json {
        @acros = Post.find_by_room(Settings.mmr.acros.name, :order => "created_at DESC")
        @prism = Post.find_by_room(Settings.mmr.prism.name, :order => "created_at DESC")
        @media = Post.find_by_room(Settings.mmr.media.name, :order => "created_at DESC")
        @other = Post.find_by_room(Settings.mmr.other.name, :order => "created_at DESC")

        @acros = @acros.to_api unless @acros.nil?
        @prism = @prism.to_api unless @prism.nil?
        @media = @media.to_api unless @media.nil?
        @other = @other.to_api unless @other.nil?

        @posts = { Settings.mmr.acros.name => @acros, Settings.mmr.prism.name => @prism, Settings.mmr.media.name => @media, Settings.mmr.other.name=> @other }
        render :json => @posts
      }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @acros = Post.find_by_room(Settings.mmr.acros.name, :order => "created_at DESC")
    @prism = Post.find_by_room(Settings.mmr.prism.name, :order => "created_at DESC")
    @media = Post.find_by_room(Settings.mmr.media.name, :order => "created_at DESC")
    @other = Post.find_by_room(Settings.mmr.other.name, :order => "created_at DESC")

    @acros = @acros.nil? ? -1 : @acros.to_api['outdated'] ? -1 : @acros[:rate]
    @prism = @prism.nil? ? -1 : @prism.to_api['outdated'] ? -1 : @prism[:rate]
    @media = @media.nil? ? -1 : @media.to_api['outdated'] ? -1 : @media[:rate]
    @other = @other.nil? ? -1 : @other.to_api['outdated'] ? -1 : @other[:rate]

    respond_to do |format|
      format.html
    end
  end
end

app/controllers/posts_controller.rb
# -*- coding: utf-8 -*-
class PostsController < ApplicationController
  before_filter :authenticate_user!

  # GET /posts
  # GET /posts.json
  def index

    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    
    # 計算
    @tmp = calc(params[:post])
    @post = Post.new(@tmp)

    respond_to do |format|
      if @post.valid?
        if @post.save
          format.html { redirect_to @post, :notice => 'Post was successfully created.' }
          format.json { render :json => @post, :status => :created, :location => @post }
        end
      else
        format.html { render :action => "new" }
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    
    @post = Post.find(params[:id])
    @tmp = calc(params[:post])

    respond_to do |format|
        if @post.update_attributes(@tmp)
          if @post.valid?
          # 計算
          @post = calc(@post)

          # 更新(気合)
          @post.update_attribute(:rate, @post.rate)
          @post.update_attribute(:windows, @post.windows)
          @post.update_attribute(:linux, @post.linux)

          format.html { redirect_to @post, :notice => 'Post was successfully updated.' }
          format.json { head :no_content }
        end
      else
          format.html { render :action => "edit" }
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  # 計算
  def calc(params)

    # 部屋の最大人数に関して
    if params[:room] == Settings.mmr.acros.name
      params[:available] = Settings.mmr.acros.size - params[:unavailable].to_i
    elsif params[:room] == Settings.mmr.prism.name
      params[:available] = Settings.mmr.prism.size - params[:unavailable].to_i
    elsif params[:room] == Settings.mmr.media.name
      params[:available] = Settings.mmr.media.size - params[:unavailable].to_i
    elsif params[:room] == Settings.mmr.other.name
      params[:available] = Settings.mmr.other.size - params[:unavailable].to_i
    end

    # 利用率に関して
    if params[:calc_base]           # 利用証ベース
      params[:rate] = (params[:available].to_i - params[:users].to_i).to_f / params[:available].to_i * 100
      if params[:windows] != "" && params[:linux] != "" && (params[:windows].to_i != 0 && params[:linux].to_i != 0)
        params[:windows] = (params[:windows].to_f / (params[:windows].to_i + params[:linux].to_i)) * (params[:available].to_i - params[:users].to_i)
        params[:linux] = (params[:available].to_i - params[:users].to_i) - params[:windows].to_i
      end
    else                        # 利用者ベース
      params[:rate] = params[:users].to_f / params[:available].to_i * 100
      if params[:windows] != "" && params[:linux] != "" && (params[:windows] != 0 && params[:linux] != 0)
        params[:windows] = (params[:windows].to_f / (params[:windows].to_i + params[:linux].to_i)) * params[:users].to_i
        params[:linux] = params[:users].to_i - params[:windows].to_i
      end
    end

    return params
  end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<% if user_signed_in? %>
<%= link_to "ログアウト", destroy_user_session_path, :method => :delete, :class => "btn btn-danger btn-large" %>
<% else %>
<%= link_to "ログイン", new_user_session_path, :class => "btn btn-large btn-primary" %>
<% end %>

app/views/layouts/api.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "RsCalc" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>
    <%= bootstrap_flash %>
    <%= yield %>


    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "RsCalc" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>
    <div class="navbar navbar-inverse">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "RsCalc", posts_path, :class => "brand" %>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "新規登録", new_post_path %></li>
              <li><%= link_to "グラフ表示", "#"  %></li>
              <li><%= link_to "検索", "#"  %></li>
            </ul>
            <ul class="nav pull-right">
                <% if user_signed_in? %>
                <%= link_to "Logout", destroy_user_session_path, :method => :delete, :class => "btn btn-danger" %>
                <% else %>
                <%= link_to "Login", new_user_session_path, :class => "btn btn-primary" %>
                <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <!-- <p class="notice"><%= notice %></p> -->
    <!-- <p class="alert"><%= alert %></p> -->

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "新規登録", new_post_path %></li>
              <li><%= link_to "グラフ表示", "#" %></li>
              <li><%= link_to "検索", "#"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <hr>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "RsCalc" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>
    <div class="navbar navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "RsCalc", root_path, :class => "brand" %>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
            <ul class="nav pull-right">
              <% if user_signed_in? %>
              <%= link_to "Logout", destroy_user_session_path, :method => :delete, :class => "btn btn-danger" %>
              <% else %>
              <%= link_to "Login", new_user_session_path, :class => "btn btn-primary" %>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">
        <h1>Rainbow Activity Ratio</h1>
        <br>
        <p>
          ここでは立命館大学びわこ・くさつキャンパスにある三つのマルチメディアルーム(MMR)の利用状況を掲載しています．
        </p>
      </div>

      <!-- Example row of columns -->
      <div class="row">
        <div class="span4">
          <h2>アクロスウィング</h2>
          <p>利用率: <%= @acros == -1 ? "利用状況不明" : "#{@acros}%" %></p>
          <% if @acros != -1 %>
          <div id="Acros_MMR"></div>
          <% else %>
          <%= image_tag '/assets/outdated.png' %>
          <% end %>
          <p><a class="btn" href="#">詳細情報 &raquo;</a></p>
        </div>
        <div class="span4">
          <h2>プリズムハウス</h2>
          <p>利用率: <%= @prism == -1 ? "利用状況不明" : "#{@prism}%" %></p>
          <% if @prism != -1 %>
          <div id="Prism_MMR"></div>
          <% else %>
          <%= image_tag '/assets/outdated.png' %>
          <% end %>
          <p><a class="btn" href="#">詳細情報 &raquo;</a></p>
        </div>
        <div class="span4">
          <h2>メディアセンター</h2>
          <p>利用率: <%= @media == -1 ? "利用状況不明" : "#{@media}%" %></p>
          <% if @media != -1 %>
          <div id="Media_MMR"></div>
          <% else %>
          <%= image_tag '/assets/outdated.png' %>
          <% end %>
          <p><a class="btn" href="#">詳細情報 &raquo;</a></p>
        </div>
      </div>

      <hr>

      <footer>
        <p>&copy; Company 2012</p>
      </footer>
    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <script type='text/javascript' src='https://www.google.com/jsapi'></script>
    <script type='text/javascript'>
      google.load('visualization', '1', {packages:['gauge']});
      google.setOnLoadCallback(drawChart);
      function drawChart() {
        var data_acros = google.visualization.arrayToDataTable([
          ['Label', 'Value'],
          ['利用率', 70],
        ]);
        var data_prism = google.visualization.arrayToDataTable([
          ['Label', 'Value'],
          ['利用率', 90],
        ]);
        var data_media = google.visualization.arrayToDataTable([
          ['Label', 'Value'],
          ['利用率', 100],
        ]);

        var options = {
          width: 400, height: 200,
          redFrom: 90, redTo: 100,
          yellowFrom:75, yellowTo: 90,
          greenFrom: 60, greenTo: 75,
          minorTicks: 5
        };

        if (document.getElementById('Acros_MMR') != null) {
          var chart_acros = new google.visualization.Gauge(document.getElementById('Acros_MMR'));
          chart_acros.draw(data_acros, options);
        }

        if (document.getElementById('Prism_MMR') != null) {
          var chart_prism = new google.visualization.Gauge(document.getElementById('Prism_MMR'));
          chart_prism.draw(data_prism, options);
        }

        if (document.getElementById('Media_MMR') != null) {
          var chart_media = new google.visualization.Gauge(document.getElementById('Media_MMR'));
          chart_media.draw(data_media, options);
        }
      }
    </script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :room, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :room, [Settings.mmr.acros.name, Settings.mmr.prism.name, Settings.mmr.media.name, Settings.mmr.other.name] %>
    </div>
  </div>

  <div class="control-group <%= @post.errors[:users].empty? ? '' : 'error' %>">
    <%= f.label "利用者数", :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :users, :class => 'number_field' %>
    </div>
  </div>

  <div class="control-group <%= @post.errors[:unavailable].empty? ? '' : 'error' %>">
    <%= f.label "利用不可端末", :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :unavailable, :class => 'number_field' %>
    </div>
  </div>

  <div class="control-group <%= @post.errors[:windows].empty? ? '' : 'error' %>">
    <%= f.label "Windows", :class => 'control-label' %>
    <div class="controls">
        <%= f.number_field :windows, :class => 'number_field' %>
    </div>
  </div>

  <div class="control-group <%= @post.errors[:linux].empty? ? '' : 'error' %>">
    <%= f.label "Linux", :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :linux, :class => 'number_field'%>
    </div>
  </div>

  <div class="control-group">
    <%= f.label "利用証から計算", :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :calc_base, {:checked => false}, true, false %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                posts_path, :class => 'btn' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/index.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <!-- <th><%= model_class.human_attribute_name(:id) %></th> -->
      <th><%= model_class.human_attribute_name(:room) %></th>
      <th><%= model_class.human_attribute_name(:rate) %>(%)</th>
      <!-- <th><%= model_class.human_attribute_name(:available) %></th> -->
      <!-- <th><%= model_class.human_attribute_name(:unavailable) %></th> -->
      <th><%= model_class.human_attribute_name(:windows) %>(台)</th>
      <th><%= model_class.human_attribute_name(:linux) %>(台)</th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <!-- <td><%= link_to post.id, post_path(post) %></td> -->
        <td><%= post.room %></td>
        <td><%= post.rate %></td>
        <!-- <td><%= post.available %></td> -->
        <!-- <td><%= post.unavailable %></td> -->
        <td><%= post.windows %></td>
        <td><%= post.linux %></td>
        <td><%=l post.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_post_path(post), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      post_path(post),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_post_path,
            :class => 'btn btn-primary' %>

app/views/posts/new.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/show.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:room) %>:</strong></dt>
  <dd><%= @post.room %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rate) %>:</strong></dt>
  <dd><%= @post.rate %>%</dd>
  <!-- <dt><strong><%= model_class.human_attribute_name(:available) %>:</strong></dt> -->
  <!-- <dd><%= @post.available %></dd> -->
  <dt><strong><%= model_class.human_attribute_name(:unavailable) %>:</strong></dt>
  <dd><%= @post.unavailable %></dd>
  <dt><strong><%= model_class.human_attribute_name(:windows) %>:</strong></dt>
  <dd><%= @post.windows %>台</dd>
  <dt><strong><%= model_class.human_attribute_name(:linux) %>:</strong></dt>
  <dd><%= @post.linux %>台</dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              posts_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_post_path(@post), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              post_path(@post),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>